// Generated by scripts/extract.mjs from source/qta-site.html. Do not edit by hand.
// Topic -> jurisdiction -> { t: plain-terms duty, l: links }

export type Jurisdiction = "gb" | "ni" | "ie"
export type LawLink = { n: string; u: string }
export type LawEntry = { t: string; l: LawLink[] }
export type LawTopic = { label: string } & Record<Jurisdiction, LawEntry>

export const JN: Record<Jurisdiction, string> = {
    "gb": "Great Britain",
    "ni": "Northern Ireland",
    "ie": "Ireland"
}

export const LAW: Record<string, LawTopic> = {
    "general": {
        "label": "General duties",
        "gb": {
            "t": "Employers must protect employees and anyone else affected by the work, so far as is reasonably practicable.",
            "l": [
                {
                    "n": "Health and Safety at Work etc. Act 1974",
                    "u": "https://www.legislation.gov.uk/ukpga/1974/37/contents"
                }
            ]
        },
        "ni": {
            "t": "Employers must protect employees and anyone else affected by the work, so far as is reasonably practicable.",
            "l": [
                {
                    "n": "Health and Safety at Work (NI) Order 1978",
                    "u": "https://www.legislation.gov.uk/nisi/1978/1039/contents"
                },
                {
                    "n": "HSENI",
                    "u": "https://www.hseni.gov.uk/"
                }
            ]
        },
        "ie": {
            "t": "Employers must manage work so that employees and others are safe, and keep a written safety statement.",
            "l": [
                {
                    "n": "Safety, Health and Welfare at Work Act 2005",
                    "u": "https://www.irishstatutebook.ie/eli/2005/act/10/enacted/en/html"
                },
                {
                    "n": "Health and Safety Authority",
                    "u": "https://www.hsa.ie/"
                }
            ]
        }
    },
    "risk": {
        "label": "Risk assessment",
        "gb": {
            "t": "Assess the risks to staff and the public. Record the significant findings if you employ five or more.",
            "l": [
                {
                    "n": "Management of Health and Safety at Work Regulations 1999",
                    "u": "https://www.legislation.gov.uk/uksi/1999/3242/contents"
                },
                {
                    "n": "HSE: managing risks",
                    "u": "https://www.hse.gov.uk/simple-health-safety/risk/"
                }
            ]
        },
        "ni": {
            "t": "Assess the risks to staff and the public. Record the significant findings if you employ five or more.",
            "l": [
                {
                    "n": "Management of Health and Safety at Work Regulations (NI) 2000",
                    "u": "https://www.legislation.gov.uk/nisr/2000/388/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Every employer must have a written risk assessment and a safety statement based on it.",
            "l": [
                {
                    "n": "Safety, Health and Welfare at Work Act 2005",
                    "u": "https://www.irishstatutebook.ie/eli/2005/act/10/enacted/en/html"
                },
                {
                    "n": "BeSMART.ie, the HSA risk assessment tool",
                    "u": "https://www.besmart.ie/"
                }
            ]
        }
    },
    "fire": {
        "label": "Fire safety",
        "gb": {
            "t": "The responsible person must carry out a fire risk assessment, keep it under review and act on it. Scotland has its own Act.",
            "l": [
                {
                    "n": "Regulatory Reform (Fire Safety) Order 2005 (England and Wales)",
                    "u": "https://www.legislation.gov.uk/uksi/2005/1541/contents"
                },
                {
                    "n": "Fire (Scotland) Act 2005",
                    "u": "https://www.legislation.gov.uk/asp/2005/5/contents"
                },
                {
                    "n": "GOV.UK: workplace fire safety",
                    "u": "https://www.gov.uk/workplace-fire-safety-your-responsibilities"
                }
            ]
        },
        "ni": {
            "t": "The appropriate person must carry out a fire risk assessment, keep it under review and act on it.",
            "l": [
                {
                    "n": "Fire and Rescue Services (NI) Order 2006",
                    "u": "https://www.legislation.gov.uk/nisi/2006/1254/contents"
                },
                {
                    "n": "Fire Safety Regulations (NI) 2010",
                    "u": "https://www.legislation.gov.uk/nisr/2010/325/contents/made"
                },
                {
                    "n": "NIFRS: business fire safety",
                    "u": "https://www.nifrs.org/home/staying-safe/business-fire-safety/"
                }
            ]
        },
        "ie": {
            "t": "Whoever controls the premises must guard against fire and keep people safe if one breaks out. Fire is also part of your risk assessment.",
            "l": [
                {
                    "n": "Fire Services Act 1981",
                    "u": "https://www.irishstatutebook.ie/eli/1981/act/30/enacted/en/html"
                },
                {
                    "n": "Safety, Health and Welfare at Work Act 2005",
                    "u": "https://www.irishstatutebook.ie/eli/2005/act/10/enacted/en/html"
                }
            ]
        }
    },
    "coshh": {
        "label": "Hazardous substances",
        "gb": {
            "t": "Assess every hazardous substance you use, prevent or control exposure and train your staff.",
            "l": [
                {
                    "n": "COSHH Regulations 2002",
                    "u": "https://www.legislation.gov.uk/uksi/2002/2677/contents"
                },
                {
                    "n": "HSE: COSHH",
                    "u": "https://www.hse.gov.uk/coshh/"
                },
                {
                    "n": "HSE: hairdressing",
                    "u": "https://www.hse.gov.uk/hairdressing/"
                }
            ]
        },
        "ni": {
            "t": "Assess every hazardous substance you use, prevent or control exposure and train your staff.",
            "l": [
                {
                    "n": "COSHH Regulations (NI) 2003",
                    "u": "https://www.legislation.gov.uk/nisr/2003/34/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Assess the chemical agents you use, prevent or control exposure and train your staff.",
            "l": [
                {
                    "n": "Chemical Agents Regulations 2001",
                    "u": "https://www.irishstatutebook.ie/eli/2001/si/619/made/en/print"
                }
            ]
        }
    },
    "equip": {
        "label": "Work equipment and operator training",
        "gb": {
            "t": "Equipment must be suitable and maintained, and everyone who uses it must be adequately trained.",
            "l": [
                {
                    "n": "PUWER 1998",
                    "u": "https://www.legislation.gov.uk/uksi/1998/2306/contents"
                },
                {
                    "n": "HSE: PUWER",
                    "u": "https://www.hse.gov.uk/work-equipment-machinery/puwer.htm"
                }
            ]
        },
        "ni": {
            "t": "Equipment must be suitable and maintained, and everyone who uses it must be adequately trained.",
            "l": [
                {
                    "n": "PUWER (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/305/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Equipment must be suitable and maintained, and everyone who uses it must be trained and instructed.",
            "l": [
                {
                    "n": "General Application Regulations 2007",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "trucks": {
        "label": "Lift trucks",
        "gb": {
            "t": "Operators need basic, specific job and familiarisation training before they work unsupervised.",
            "l": [
                {
                    "n": "PUWER 1998",
                    "u": "https://www.legislation.gov.uk/uksi/1998/2306/contents"
                },
                {
                    "n": "HSE L117: rider-operated lift trucks",
                    "u": "https://www.hse.gov.uk/pubns/books/l117.htm"
                }
            ]
        },
        "ni": {
            "t": "Operators need adequate training on the truck type they use before they work unsupervised.",
            "l": [
                {
                    "n": "PUWER (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/305/contents/made"
                },
                {
                    "n": "LOLER (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/304/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Operators must be trained and competent on the type of truck they use.",
            "l": [
                {
                    "n": "General Application Regulations 2007",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "lifting": {
        "label": "Lifting operations",
        "gb": {
            "t": "Lifts must be planned, supervised and carried out safely by competent people, with equipment thoroughly examined.",
            "l": [
                {
                    "n": "LOLER 1998",
                    "u": "https://www.legislation.gov.uk/uksi/1998/2307/contents"
                },
                {
                    "n": "HSE: LOLER",
                    "u": "https://www.hse.gov.uk/work-equipment-machinery/loler.htm"
                }
            ]
        },
        "ni": {
            "t": "Lifts must be planned, supervised and carried out safely by competent people, with equipment thoroughly examined.",
            "l": [
                {
                    "n": "LOLER (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/304/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Lifting equipment must be examined and lifting operations planned and carried out by competent people.",
            "l": [
                {
                    "n": "General Application Regulations 2007",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "height": {
        "label": "Work at height",
        "gb": {
            "t": "Avoid work at height where you can. Where you cannot, plan it, use the right equipment and use competent people.",
            "l": [
                {
                    "n": "Work at Height Regulations 2005",
                    "u": "https://www.legislation.gov.uk/uksi/2005/735/contents"
                },
                {
                    "n": "HSE: work at height",
                    "u": "https://www.hse.gov.uk/work-at-height/"
                }
            ]
        },
        "ni": {
            "t": "Avoid work at height where you can. Where you cannot, plan it, use the right equipment and use competent people.",
            "l": [
                {
                    "n": "Work at Height Regulations (NI) 2005",
                    "u": "https://www.legislation.gov.uk/nisr/2005/279/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Avoid work at height where you can. Where you cannot, plan it, use the right equipment and use competent people.",
            "l": [
                {
                    "n": "General Application Regulations 2007, Part 4",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "confined": {
        "label": "Confined spaces",
        "gb": {
            "t": "Avoid entry if possible. If not, follow a safe system of work and have rescue arrangements ready first.",
            "l": [
                {
                    "n": "Confined Spaces Regulations 1997",
                    "u": "https://www.legislation.gov.uk/uksi/1997/1713/contents"
                },
                {
                    "n": "HSE: confined spaces",
                    "u": "https://www.hse.gov.uk/confinedspace/"
                }
            ]
        },
        "ni": {
            "t": "Avoid entry if possible. If not, follow a safe system of work and have rescue arrangements ready first.",
            "l": [
                {
                    "n": "Confined Spaces Regulations (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/13/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Avoid entry if possible. If not, follow a safe system of work and have rescue arrangements ready first.",
            "l": [
                {
                    "n": "Confined Spaces Regulations 2001",
                    "u": "https://www.irishstatutebook.ie/eli/2001/si/218/made/en/print"
                }
            ]
        }
    },
    "construction": {
        "label": "Construction",
        "gb": {
            "t": "Clients, designers and contractors each have duties to plan, manage and monitor construction work safely.",
            "l": [
                {
                    "n": "CDM Regulations 2015",
                    "u": "https://www.legislation.gov.uk/uksi/2015/51/contents"
                },
                {
                    "n": "HSE: CDM 2015",
                    "u": "https://www.hse.gov.uk/construction/cdm/2015/index.htm"
                }
            ]
        },
        "ni": {
            "t": "Clients, designers and contractors each have duties to plan, manage and monitor construction work safely.",
            "l": [
                {
                    "n": "CDM Regulations (NI) 2016",
                    "u": "https://www.legislation.gov.uk/nisr/2016/146/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Clients, designers and contractors have duties, and site workers need recognised safety awareness training.",
            "l": [
                {
                    "n": "Construction Regulations 2013",
                    "u": "https://www.irishstatutebook.ie/eli/2013/si/291/made/en/print"
                },
                {
                    "n": "SOLAS: Safe Pass",
                    "u": "https://www.solas.ie/construction-lp/safe-pass/"
                }
            ]
        }
    },
    "abrasive": {
        "label": "Abrasive wheels",
        "gb": {
            "t": "Anyone who mounts or uses abrasive wheels must be trained and competent to do so.",
            "l": [
                {
                    "n": "PUWER 1998",
                    "u": "https://www.legislation.gov.uk/uksi/1998/2306/contents"
                },
                {
                    "n": "HSE HSG17: safety in the use of abrasive wheels",
                    "u": "https://www.hse.gov.uk/pubns/books/hsg17.htm"
                }
            ]
        },
        "ni": {
            "t": "Anyone who mounts or uses abrasive wheels must be trained and competent to do so.",
            "l": [
                {
                    "n": "PUWER (NI) 1999",
                    "u": "https://www.legislation.gov.uk/nisr/1999/305/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Anyone who mounts or uses abrasive wheels must be trained and competent to do so.",
            "l": [
                {
                    "n": "General Application Regulations 2007",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "ppe": {
        "label": "PPE",
        "gb": {
            "t": "Where a risk cannot be controlled another way, the employer must provide suitable PPE free of charge and train people to use it.",
            "l": [
                {
                    "n": "Personal Protective Equipment at Work Regulations 1992",
                    "u": "https://www.legislation.gov.uk/uksi/1992/2966/contents"
                },
                {
                    "n": "HSE: PPE at work",
                    "u": "https://www.hse.gov.uk/ppe/"
                }
            ]
        },
        "ni": {
            "t": "Where a risk cannot be controlled another way, the employer must provide suitable PPE free of charge and train people to use it.",
            "l": [
                {
                    "n": "Personal Protective Equipment at Work Regulations (NI) 1993",
                    "u": "https://www.legislation.gov.uk/nisr/1993/20/contents/made"
                }
            ]
        },
        "ie": {
            "t": "Where a risk cannot be controlled another way, the employer must provide suitable PPE free of charge and train people to use it.",
            "l": [
                {
                    "n": "General Application Regulations 2007",
                    "u": "https://www.irishstatutebook.ie/eli/2007/si/299/made/en/print"
                }
            ]
        }
    },
    "drain": {
        "label": "Septic tank discharges",
        "gb": {
            "t": "In England, small sewage discharges must meet the general binding rules or hold a permit. Scotland and Wales have their own regulators.",
            "l": [
                {
                    "n": "GOV.UK: septic tanks and treatment plants",
                    "u": "https://www.gov.uk/permits-you-need-for-septic-tanks"
                }
            ]
        },
        "ni": {
            "t": "A discharge from a septic tank or treatment plant needs consent to discharge from DAERA under the Water (NI) Order 1999.",
            "l": [
                {
                    "n": "DAERA: regulating water discharges",
                    "u": "https://www.daera-ni.gov.uk/articles/regulating-water-discharges"
                }
            ]
        },
        "ie": {
            "t": "Domestic waste water treatment systems must be registered and maintained so they do not pollute.",
            "l": [
                {
                    "n": "Protect Our Water: registration",
                    "u": "https://www.protectourwater.ie/"
                },
                {
                    "n": "EPA",
                    "u": "https://www.epa.ie/"
                }
            ]
        }
    }
}
