// Pulls LAW, COURSES and the dates table out of source/qta-site.html so the
// Framer build uses the prototype's data verbatim. Re-run after editing the prototype.
//   node scripts/extract.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import vm from "node:vm"

const root = new URL("..", import.meta.url)
const html = readFileSync(new URL("source/qta-site.html", root), "utf8")

export function loadPrototypeData(src = html) {
    const script = src.match(/<script>([\s\S]*?)<\/script>/)[1]
    // Run only the data declarations, not the DOM code that follows them.
    const data = script.slice(script.indexOf("var L="), script.indexOf("var JN="))
    const ctx = {}
    vm.runInNewContext(data + ";this.LAW=LAW;this.COURSES=COURSES;", ctx)
    const JN = vm.runInNewContext("(" + script.match(/var JN=(\{[^}]*\})/)[1] + ")")

    const tbody = src.match(/<section id="dates"[\s\S]*?<tbody>([\s\S]*?)<\/tbody>/)[1]
    const dates = [...tbody.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map((row) => {
        const cells = [...row[1].matchAll(/<td>([\s\S]*?)<\/td>/g)].map((c) =>
            c[1].replace(/<[^>]+>/g, "").trim()
        )
        return { course: cells[0], window: cells[1], location: cells[2], status: cells[3] }
    })
    return { LAW: ctx.LAW, COURSES: ctx.COURSES, JN, dates }
}

const slug = (s) =>
    s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

const csv = (rows) =>
    rows
        .map((r) => r.map((v) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)).join(","))
        .join("\n") + "\n"

if (import.meta.url === `file://${process.argv[1]}`) {
    const { LAW, COURSES, JN, dates } = loadPrototypeData()

    writeFileSync(
        new URL("framer/code/lawData.tsx", root),
        "// Generated by scripts/extract.mjs from source/qta-site.html. Do not edit by hand.\n" +
            "// Topic -> jurisdiction -> { t: plain-terms duty, l: links }\n\n" +
            "export type Jurisdiction = \"gb\" | \"ni\" | \"ie\"\n" +
            "export type LawLink = { n: string; u: string }\n" +
            "export type LawEntry = { t: string; l: LawLink[] }\n" +
            "export type LawTopic = { label: string } & Record<Jurisdiction, LawEntry>\n\n" +
            `export const JN: Record<Jurisdiction, string> = ${JSON.stringify(JN, null, 4)}\n\n` +
            `export const LAW: Record<string, LawTopic> = ${JSON.stringify(LAW, null, 4)}\n`
    )

    mkdirSync(new URL("framer/cms", root), { recursive: true })
    const courses = COURSES.map((c, i) => ({
        slug: slug(c.n),
        name: c.n,
        category: c.c,
        description: c.d,
        lawTopics: c.k.join(","),
        order: i + 1,
    }))
    const datesOut = dates.map((d, i) => ({ slug: slug(`${d.course} ${d.window}`), ...d, order: i + 1 }))
    writeFileSync(new URL("framer/cms/courses.json", root), JSON.stringify(courses, null, 2) + "\n")
    writeFileSync(new URL("framer/cms/dates.json", root), JSON.stringify(datesOut, null, 2) + "\n")
    writeFileSync(
        new URL("framer/cms/courses.csv", root),
        csv([
            ["Slug", "Name", "Category", "Description", "Law topics", "Order"],
            ...courses.map((c) => [c.slug, c.name, c.category, c.description, c.lawTopics, String(c.order)]),
        ])
    )
    writeFileSync(
        new URL("framer/cms/dates.csv", root),
        csv([
            ["Slug", "Course", "Window", "Location", "Status", "Order"],
            ...datesOut.map((d) => [d.slug, d.course, d.window, d.location, d.status, String(d.order)]),
        ])
    )
    console.log(`LAW topics: ${Object.keys(LAW).length}, courses: ${courses.length}, dates: ${datesOut.length}`)
}
